apiVersion: v1
kind: Secret
metadata:
  name: smsemailfront-secret
  namespace: desarrolloem
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smsemailfront-configmap
  namespace: desarrolloem
data:
  REACT_APP_API: 'http://smsservices-nm-ivr-evolucion-dev.apps.claro.co/'
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: smsemailfront
    legado: SMSEMAILSERVICES
    proyecto: WHATSAPP
    subproyecto: COMPRADEPAQUETES
    tecnologia: NodeJS
  name: smsemailfront
  namespace: desarrolloem
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: smsemailfront
    deploymentconfig: smsemailfront
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      limits:
        cpu: 100m
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 250Mi
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: smsemailfront
        deploymentconfig: smsemailfront
      name : smsemailfront
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: smsemailfront-configmap
            - secretRef:
                name: smsemailfront-secret
          image: docker-registry.default.svc:5000/desarrolloem/smsemailfront@sha256:8124076b6ddc0ff87a07c0bfaadfdec45b286a5cfdd1e37255284390938692e8
          imagePullPolicy: IfNotPresent
          name: smsemailfront
          ports:
            - name : service-port
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 250Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: smsemailfront
  name: smsemailfront
  namespace: desarrolloem
spec:
  ports:
    - name : service-port
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: smsemailfront
    deploymentconfig: smsemailfront
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: smsemailfront
  name: smsemailfront
  namespace: desarrolloem
spec:
  port:
    targetPort: service-port
  to:
    kind: Service
    name: smsemailfront
    weight: 100
  wildcardPolicy: None